# Generated by Django 3.2.17 on 2023-02-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='maxtempofday',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='mintempofday',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='precipofday',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='yieldoftheyear',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
