# Generated by Django 3.2.17 on 2023-02-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0004_alter_weatherdata_weatherstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxAverageTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averageMaxTemp', models.IntegerField(blank=True, default=None, null=True)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('weatherstation', models.CharField(blank=True, default=None, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinAverageTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('averageMinTemp', models.IntegerField(blank=True, default=None, null=True)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('weatherstation', models.CharField(blank=True, default=None, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Totalprecipitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Totalprecipitation', models.IntegerField(blank=True, default=None, null=True)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('weatherstation', models.CharField(blank=True, default=None, max_length=16, null=True)),
            ],
        ),
    ]
