# Generated by Django 3.2.17 on 2023-02-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0006_auto_20230213_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
