# Generated by Django 3.2.17 on 2023-02-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0002_auto_20230212_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='weatherstation',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
