# Generated by Django 3.2.17 on 2023-02-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0003_weatherdata_weatherstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='weatherstation',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
