# Generated by Django 3.2.17 on 2023-02-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeapp', '0007_weatherdata_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='year',
            new_name='theyear',
        ),
    ]
